version: '3.8'
services:
  storedb:
    image: mysql:8.3.0
    env_file:
      - env/mysql.env
    volumes:
      - storedb-data:/var/lib/mysql
    networks:
      - store-network

  rabbitmq:
    image: rabbitmq:3.13.0
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - store-network

  notifications-api:
    build: 
      context: ./notifications-api
    ports:
      - "5001:5001"
    env_file:
      - env/rabbit.env
    depends_on:
      - rabbitmq
    networks:
      - store-network

  products-api:
    build: 
      context: ./products-api
    ports:
      - "8080:8080"
    env_file:
      - env/products-api.env
      - env/rabbit.env
    depends_on:
      - storedb
      - notifications-api
    networks:
      - store-network

  store-frontend:
    build: 
      context: ./store-frontend
    ports:
      - "3000:3000"
    depends_on:
      - products-api
    stdin_open: true
    tty: true
    networks:
      - store-network

volumes:
  storedb-data:
  rabbitmq-data:

networks:
  store-network:
    driver: bridge