apiVersion: apps/v1
kind: Deployment
metadata:
  name: storedb
spec:
  replicas: 1
  selector:
    matchLabels:
      component: database
  template:
    metadata:
      labels:
        component: database
    spec:
      containers:
        - name: mysql
          image: mysql:8.3.0
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: mysql-configmap
          # env:
          #   - name: MYSQL_USERNAME
          #     valueFrom:
          #       secretKeyRef:
          #         name: mysql-secret
          #         key: MYSQL_USERNAME
          #   - name: MYSQL_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: mysql-secret
          #         key: MYSQL_PASSWORD
          volumeMounts:
            - name: mysql-storage
              mountPath: /data/storedb
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc