apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster-ip-service
spec:
  ports:
    - name: storedb
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    component: database