apiVersion: v1
kind: Service
metadata:
  name: notifications-api-service
spec:
  selector:
    app: notifications-api
  ports:
    - name: api
      protocol: TCP
      port: 5001
      targetPort: 5001
    - name: messaging
      protocol: TCP
      port: 5672
      targetPort: 5672