apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-configmap
data:
  RABBITMQ_HOST: "rabbitmq-cluster-ip-service"
  # RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_QUEUE_NAME: storeQueue